name: CI

on:

  pull_request:
    branches:
      - v5
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 16

      - name: Configure committer
        run: |
          git config user.name "github-actions"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Standard Version
        uses: qzb/standard-version-action@v1.0.6

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Merge to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ github.event.pull_request.title }}
